spring.application.name=exp
server.port=8081
#Property to change the context path of an application 
server.servlet.context-path=/demoapp


# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/exp_db
spring.datasource.username=postgres
spring.datasource.password=Aspire@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

